---
dist: trusty
sudo: required

language: c

services:
  - docker

before_install:
  - docker pull lcallarec/flatpak-gnome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - docker run --privileged -v $PWD:/build:rw lcallarec/flatpak-gnome /bin/bash -c "cd /build && make"
