---
dist: trusty
sudo: required

language: c

services:
  - docker

before_install:
  - docker pull lcallarec/flatpak-gnome

script:
  - docker run --privileged -v $PWD:/build:rw lcallarec/flatpak-gnome /bin/bash -c "cd /build && make"
